version: '3.8'
services:
  authorization-db:
    image: postgres:14-alpine
    container_name: authorization-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authorization